/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criotam.actionbarfiles;

import com.mysql.cj.protocol.Resultset;
import criotam.PlayerDashboardUI;
import criotam.database.PlayerDatabase;
import java.awt.Graphics;
import java.awt.Image;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author AVINASH
 */
public class CriotamUI extends javax.swing.JFrame {
    
    String url = "jdbc:mysql://localhost/criotamdb";
    String USER = "root";
    String PASS = "";

    Map<String, String> parameters;
    
    /**
     * Creates new form CriotamUI
     */
    public CriotamUI() {
        initComponents();
     
        parameters = new HashMap<>();
        this.setLocationRelativeTo(null);
    }
    
    
    public CriotamUI(String flag) {
        exit_initComponents();
        parameters = new HashMap<>();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    private void exit_initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        player_name = new javax.swing.JTextField();
        player_age = new javax.swing.JTextField();
        player_weight = new javax.swing.JTextField();
        player_height = new javax.swing.JTextField();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        player_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        jTextField3.setText("jTextField3");

        jCheckBox1.setText("jCheckBox1");

        
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255, 130));
        jPanel8.setMaximumSize(new java.awt.Dimension(440, 494));
        jPanel8.setPreferredSize(new java.awt.Dimension(440, 550));

        player_name.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_name.setForeground(new java.awt.Color(153, 153, 153));
        player_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_name.setText("Player Name");
        player_name.setToolTipText("Enter Player Name");
        player_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        player_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_nameFocusLost(evt);
            }
        });
        player_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        player_age.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_age.setForeground(new java.awt.Color(153, 153, 153));
        player_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_age.setText("Age");
        player_age.setToolTipText("Enter you age");
        player_age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_ageFocusLost(evt);
            }
        });
        player_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        player_weight.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_weight.setForeground(new java.awt.Color(153, 153, 153));
        player_weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_weight.setText("Weight");
        player_weight.setToolTipText("Enter your weight(in Kg)");
        player_weight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_weight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_weightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_weightFocusLost(evt);
            }
        });
        player_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        player_height.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_height.setForeground(new java.awt.Color(153, 153, 153));
        player_height.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_height.setText("Height");
        player_height.setToolTipText("Enter your height(in m)");
        player_height.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_height.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_heightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_heightFocusLost(evt);
            }
        });
        player_height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        male_radio.setBackground(new java.awt.Color(255, 255, 255, 0));
        buttonGroup1.add(male_radio);
        male_radio.setOpaque(false);

        female_radio.setBackground(new java.awt.Color(255, 255, 255, 0));
        buttonGroup1.add(female_radio);
        female_radio.setOpaque(false);
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("NEXT");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        player_id.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_id.setForeground(new java.awt.Color(153, 153, 153));
        player_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_id.setText("Enter Player ID");
        player_id.setToolTipText("*Enter player ID(Must be unique)");
        player_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_idFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 83, 83));
        jLabel11.setText("PLAYER INFORMATION");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/MALE.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/FEMALE.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player_weight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(player_height)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player_id, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player_age)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(male_radio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(female_radio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54))
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(player_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_age, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_height, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(male_radio)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(female_radio)))
                .addGap(25, 25, 25)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(230, 0, 440, 550);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/Background_2.jpg"))); // NOI18N
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 550);

        pack();
    }
        
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        player_name = new javax.swing.JTextField();
        player_age = new javax.swing.JTextField();
        player_weight = new javax.swing.JTextField();
        player_height = new javax.swing.JTextField();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        player_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jTextField3.setText("jTextField3");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/drawables/back.jpg")).getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH));
        setMinimumSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255, 130));
        jPanel8.setMaximumSize(new java.awt.Dimension(440, 494));
        jPanel8.setPreferredSize(new java.awt.Dimension(440, 550));

        player_name.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_name.setForeground(new java.awt.Color(153, 153, 153));
        player_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_name.setText("Player Name");
        player_name.setToolTipText("Enter Player Name");
        player_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        player_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_nameFocusLost(evt);
            }
        });
        player_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        player_age.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_age.setForeground(new java.awt.Color(153, 153, 153));
        player_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_age.setText("Age");
        player_age.setToolTipText("Enter you age");
        player_age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_ageFocusLost(evt);
            }
        });
        player_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        player_weight.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_weight.setForeground(new java.awt.Color(153, 153, 153));
        player_weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_weight.setText("Weight");
        player_weight.setToolTipText("Enter your weight(in Kg)");
        player_weight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_weight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_weightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_weightFocusLost(evt);
            }
        });
        player_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        player_height.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_height.setForeground(new java.awt.Color(153, 153, 153));
        player_height.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_height.setText("Height");
        player_height.setToolTipText("Enter your height(in m)");
        player_height.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_height.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_heightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_heightFocusLost(evt);
            }
        });
        player_height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        male_radio.setBackground(new java.awt.Color(255, 255, 255, 0));
        buttonGroup1.add(male_radio);
        male_radio.setOpaque(false);

        female_radio.setBackground(new java.awt.Color(255, 255, 255, 0));
        buttonGroup1.add(female_radio);
        female_radio.setOpaque(false);
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("NEXT");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        player_id.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        player_id.setForeground(new java.awt.Color(153, 153, 153));
        player_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player_id.setText("Enter Player ID");
        player_id.setToolTipText("*Enter player ID(Must be unique)");
        player_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        player_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                player_idFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 83, 83));
        jLabel11.setText("PLAYER INFORMATION");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/MALE.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/FEMALE.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player_weight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(player_height)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player_id, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player_age)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(male_radio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(female_radio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54))
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(player_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_age, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player_height, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(male_radio)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(female_radio)))
                .addGap(25, 25, 25)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(230, 0, 440, 550);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/Background_2.jpg"))); // NOI18N
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String isStored = ""+false ;
        
        if(checkifuserExist(player_id.getText().toString())){
            playerExist_infoBox();
            return;
        }
        
        if(check()){

            //loadinggif.setVisible(true);
            
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
            parameters.put("player_id", player_id.getText().toString().trim());
            parameters.put("player_name", player_name.getText().toString().trim());
            parameters.put("player_age",player_age.getText().toString().trim());
            parameters.put("player_weight", player_weight.getText().toString().trim());
            parameters.put("player_height", player_height.getText().toString().trim());
            
            String valToInsert = player_id.getText().toString().trim()+":"
            +player_name.getText().toString().trim()+":"
            +player_age.getText().toString().trim()+":"
            +player_weight.getText().toString().trim()+":"
            +player_height.getText().toString().trim()+":";

            if(male_radio.isSelected()){
                valToInsert += "MALE:";
                parameters.put("player_sex", "MALE");
            }else if(female_radio.isSelected()){
                valToInsert += "FEMALE:";
                parameters.put("player_sex", "FEMALE");
            }
            
            try {
                isStored = ""+storeDataOnServer();
                storeDataOnBlockChain();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            
            valToInsert += isStored;
            
            PlayerDatabase playerDatabase = new PlayerDatabase();
            playerDatabase.InsertData(valToInsert);
            playerDatabase.closeConn();

            try {
                new PlayerDashboardUI(searchPlayer(player_id.getText().toString().trim())).setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(CriotamUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{

            System.out.println("false");
            infoBox();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void player_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_idFocusGained
        // TODO add your handling code here:
        if(player_id.getText().equalsIgnoreCase("Enter Player ID"))
            player_id.setText("");
    }//GEN-LAST:event_player_idFocusGained

    private void player_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_idFocusLost
        // TODO add your handling code here:
        if(player_id.getText().toString().trim().length()==0)
            player_id.setText("Enter Player ID");
        
    }//GEN-LAST:event_player_idFocusLost

    private void player_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_nameFocusGained
        // TODO add your handling code here:
        if(player_name.getText().equalsIgnoreCase("Player Name"))
            player_name.setText("");
    }//GEN-LAST:event_player_nameFocusGained

    private void player_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_nameFocusLost
        // TODO add your handling code here:
        if(player_name.getText().toString().trim().length()==0)
            player_name.setText("Player Name");
    }//GEN-LAST:event_player_nameFocusLost

    private void player_ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_ageFocusGained
        // TODO add your handling code here:
        if(player_age.getText().equalsIgnoreCase("Age"))
            player_age.setText("");
        
    }//GEN-LAST:event_player_ageFocusGained

    private void player_ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_ageFocusLost
        // TODO add your handling code here:
        if(player_age.getText().toString().trim().length()==0)
            player_age.setText("Age");
    }//GEN-LAST:event_player_ageFocusLost

    private void player_weightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_weightFocusGained
        // TODO add your handling code here:
        if(player_weight.getText().equalsIgnoreCase("Weight"))
            player_weight.setText("");
    }//GEN-LAST:event_player_weightFocusGained

    private void player_weightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_weightFocusLost
        // TODO add your handling code here:
        if(player_weight.getText().toString().trim().length()==0)
            player_weight.setText("Weight");
    }//GEN-LAST:event_player_weightFocusLost

    private void player_heightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_heightFocusGained
        // TODO add your handling code here:
        if(player_height.getText().equalsIgnoreCase("Height"))
            player_height.setText("");
    }//GEN-LAST:event_player_heightFocusGained

    private void player_heightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player_heightFocusLost
        // TODO add your handling code here:
        if(player_height.getText().toString().trim().length()==0)
            player_height.setText("Height");
    }//GEN-LAST:event_player_heightFocusLost

    public ResultSet searchPlayer(String id){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, USER, PASS);
            
            PreparedStatement ps = con.prepareStatement("select * from player where playerid=?");
            ps.setString(1, id);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                return rs;
            }
            
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        return null;

    }
    
    
    public boolean check(){
        
        if(player_id.getText().toString().isEmpty()){
            return false;
        }else if(player_id.getText().toString().contains("Enter Player ID")){
            return false;
        }
        
        if(player_name.getText().toString().isEmpty()){
            return false;
        }else if(player_name.getText().toString().contains("Player Name")){
            return false;
        }
        
        if(player_age.getText().toString().isEmpty()){
            return false;
        }else if(player_age.getText().toString().contains("Age")){
            return false;
        }
        
        if(player_weight.getText().toString().isEmpty()){
            return false;
        }else if(player_weight.getText().toString().contains("Weight")){
            return false;
        }
        
        if(player_height.getText().toString().isEmpty()){
            return false;
        }else if(player_height.getText().toString().contains("Height")){
            return false;
        }
        
        if(buttonGroup1.getSelection()==null){
            return false;
        }
        
        return true;
       
    }
    
    public ResultSet rs;
    
    public boolean checkifuserExist(String id){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, USER, PASS);
            
            PreparedStatement ps = con.prepareStatement("select * from player where playerid=?");
            ps.setString(1, id);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                return true;
            }
            
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        return false;
    }
    
    public static void infoBox()
    {
        JOptionPane.showMessageDialog(null, "Please enter and select all the required fields!",
                "InfoBox: " + "Invalid Inputs", JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    public static void playerExist_infoBox()
    {
        JOptionPane.showMessageDialog(null, "Please enter unique player id. This player id already exist!",
                "InfoBox: " + "Invalid inputs", JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    public boolean storeDataOnServer() throws MalformedURLException, IOException{
        
        URL url = new URL("https://us-central1-criotam-bec9b.cloudfunctions.net/addPlayer");
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        
        con.setConnectTimeout(100000);
        con.setReadTimeout(100000);
        con.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        con.setDoOutput(true);
        DataOutputStream out = new DataOutputStream(con.getOutputStream());
        out.writeBytes(ParameterStringBuilder.getParamsString(parameters));
        out.flush();
        out.close();
        
        int status = con.getResponseCode();
        if(status == 200){
            System.out.println("####################player add successful----------------------------");
            con.disconnect();
            return true;
        }
        con.disconnect();
        return false;
    }
    
    public boolean storeDataOnBlockChain() throws MalformedURLException, IOException{
        
        URL url = new URL("http://192.168.1.6:3000/api/org.criotam.prototype.sensor.addPlayer");
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        
        con.setConnectTimeout(100000);
        con.setReadTimeout(100000);
        con.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        con.setDoOutput(true);
        DataOutputStream out = new DataOutputStream(con.getOutputStream());
        out.writeBytes(ParameterStringBuilder.getParamsString(parameters));
        out.flush();
        out.close();
        
        int status = con.getResponseCode();
        if(status == 200){
            System.out.println("####################player add successful----------------------------");
            con.disconnect();
            return true;
        }
        con.disconnect();
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriotamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriotamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriotamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriotamUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriotamUI().setVisible(true);
                jButton4.requestFocusInWindow();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton female_radio;
    private static javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField player_age;
    private javax.swing.JTextField player_height;
    private javax.swing.JTextField player_id;
    private javax.swing.JTextField player_name;
    private javax.swing.JTextField player_weight;
    // End of variables declaration//GEN-END:variables
}
